//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Diagnostics;
using System.Xml.Serialization;

namespace CotSharp
{

    /// <summary>
    /// This is a Cursor On Target detail sub-schema that holds "fingerprints" of the system 
    /// that have processed a particular CoT event.  This information aids in the routine of 
    /// CoT messages along a particular processing chain.  Each system that touches a 
    /// particular CoT event is expected to add its own attribute to this entity.  The 
    /// attribute name should reflect the particular system name, and the value should be the 
    /// time stamp when the information was sent out from that system.  Some illustrative 
    /// _flow-tags_ attributes are adocs, fbcb2, and tadilj, but the attribute list is not a 
    /// closed set.
    /// </summary>
    [DebuggerStepThrough]
    [XmlRoot("_flow-tags_")]
    [XmlType(TypeName = "_flow-tags_")]
    public partial class Flowtags
    {
        [XmlAnyElement]
        public System.Xml.XmlElement[] Any { get; set; }

        [XmlAttribute("version")]
        public decimal Version { get; set; }

        [XmlIgnore]
        public bool VersionSpecified { get; set; }

        [XmlAnyAttribute]
        public System.Xml.XmlAttribute[] AnyAttr { get; set; }
    }

}