//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Diagnostics;
using System.Xml.Serialization;

namespace CotSharp
{

    [DebuggerStepThrough]
    [XmlRoot("shapePolyline")]
    [XmlType(TypeName = "shapePolyline")]
    public partial class ShapePolyline
    {

        private ShapePolylineVertex[] vertexField;

        private string levelField;

        private bool closedField;

        public ShapePolyline()
        {
            this.closedField = true;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("vertex")]
        public ShapePolylineVertex[] vertex
        {
            get
            {
                return this.vertexField;
            }
            set
            {
                this.vertexField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string level
        {
            get
            {
                return this.levelField;
            }
            set
            {
                this.levelField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool closed
        {
            get
            {
                return this.closedField;
            }
            set
            {
                this.closedField = value;
            }
        }
    }

}