//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Diagnostics;
using System.Xml.Serialization;

namespace CotSharp
{

    [DebuggerStepThrough]
    [XmlRoot("track")]
    [XmlType(TypeName = "track")]
    public partial class Track
    {

        private System.Xml.XmlElement[] anyField;

        private decimal courseField;

        private decimal speedField;

        private decimal slopeField;

        private bool slopeFieldSpecified;

        private decimal eCourseField;

        private bool eCourseFieldSpecified;

        private decimal eSpeedField;

        private bool eSpeedFieldSpecified;

        private decimal eSlopeField;

        private bool eSlopeFieldSpecified;

        private decimal versionField;

        private bool versionFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal course
        {
            get
            {
                return this.courseField;
            }
            set
            {
                this.courseField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal speed
        {
            get
            {
                return this.speedField;
            }
            set
            {
                this.speedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal slope
        {
            get
            {
                return this.slopeField;
            }
            set
            {
                this.slopeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool slopeSpecified
        {
            get
            {
                return this.slopeFieldSpecified;
            }
            set
            {
                this.slopeFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal eCourse
        {
            get
            {
                return this.eCourseField;
            }
            set
            {
                this.eCourseField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool eCourseSpecified
        {
            get
            {
                return this.eCourseFieldSpecified;
            }
            set
            {
                this.eCourseFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal eSpeed
        {
            get
            {
                return this.eSpeedField;
            }
            set
            {
                this.eSpeedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool eSpeedSpecified
        {
            get
            {
                return this.eSpeedFieldSpecified;
            }
            set
            {
                this.eSpeedFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal eSlope
        {
            get
            {
                return this.eSlopeField;
            }
            set
            {
                this.eSlopeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool eSlopeSpecified
        {
            get
            {
                return this.eSlopeFieldSpecified;
            }
            set
            {
                this.eSlopeFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool versionSpecified
        {
            get
            {
                return this.versionFieldSpecified;
            }
            set
            {
                this.versionFieldSpecified = value;
            }
        }
    }

}