//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Diagnostics;
using System.Xml;
using System.Xml.Serialization;

namespace CotSharp
{
    /// <summary>
    /// This is a Cursor On Target detail sub-schema that holds the unique ID assigned 
    /// by each system that processed this event.  Most systems (including CoT) have their 
    /// own method for assigning system-wide unique identifiers for a particular object.  
    /// In general, it is not possible for a single UID to be used for all systems.  
    /// This 'uid' entity provides a common place where each systems can record its  
    /// particular UID for each CoT event.  Like the _flow-tags_ element, each system is 
    /// responsible for adding its own attribute to this entity.  The name of the attribute 
    /// should represent the system, and the value of the attribute should be the id that 
    /// system assigned to this CoT object.
    /// </summary>
    [DebuggerStepThrough]
    [XmlRoot("uid")]
    [XmlType(TypeName = "uid")]
    public partial class Uid
    {

        [XmlAnyElement]
        public XmlElement[] Any { get; set; }

        /// <summary>
        /// The system-specific identifier (a.k.a UID, or track number) associated with the
        /// entity described by the encapsulating CoT object.
        /// </summary>
        [XmlAttribute("version")]
        public decimal Version { get; set; }

        [XmlIgnore]
        public bool VersionSpecified { get; set; }

        /// <remarks/>
        [XmlAnyAttribute]
        public XmlAttribute[] AnyAttr { get; set; }
    }

}